### ISSUE TITLE
Discussion: Enable support for relative directories

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/ansible-role-tester#32]
Docker only supports absolute paths in volumes. Right now the `config.RemotePath` and `config.ExtraRolesPath` pass the values to docker as `--volume=%s:%v` without any processing.

Do you think it would be worth it to add extra logic to resolve relative paths? Or would you prefer to keep the code footprint minimal and encourage users to pass in well formed flags?

**Comment by fubarhouse** [comment]
I’m always in favour of simplicity, but there’s no reason complex logic can’t be added. You’ve already got the ability to add additional docker arguments.

I’d recommend creating a util file which handles the complexity and keeping it straight forward to use and read.

I’m not against it, so you’re welcome to submit a PR.

I’d probably elaborate more, I apologise - I’m using my phone.

**Comment by issmirnov** [comment]
I gave this some more thought and realized that it's actually kind of nice to have absolute path, since it makes it easier to parse the command line history and understand what was going on. Since neither of us needs this, closing the issue. Future collaborators can reopen if needed.

Thank you for being receptive to change!
