### ISSUE TITLE
Cleanup flag for failures

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/ansible-role-tester#39]
Hey, I ran into an interesting issue: when I'm iterating on a playbook, I run `ansible-role-tester` to check how it's moving along. I noticed that when the idempotence check fails, the program exists (as [expected](https://github.com/fubarhouse/ansible-role-tester/blob/master/util/idempotence.go#L57)). This leaves a ton of orphan docker containers that have to manually be cleaned up. Do you think it would be worth it to remove failed containers, or possibly add another flag or option to conditionally remove them?

**Comment by fubarhouse** [comment]
I think that would be sensible! I’ll draft something up when I get to my laptop.

I’ve also come across this, but I think it would be appropriate to allow for cleanup optionally, or to optionally not clean up by default.

**Comment by fubarhouse** [comment]
I've got a working patch for this.

I'll have a branch available for testing in the next couple of hours.

**Comment by fubarhouse** [comment]
This one could be considered now superseded by changes introduced in #2

**Comment by issmirnov** [comment]
Agreed, 1eb264d looks great. Thank you so much!
