### ISSUE TITLE
Add volumes to reports

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-tester#50]
Docker volumes aren't included in #2.

This feature would have been nice trying to diagnose some other issues 👍 

This will make the information available going forwards - noting there's also scope to include other Docker-specific configurations here.

Examples which would have benefited include #49 and #42

**Comment by fubarhouse** [comment]
This feature literally just paid for itself!

**Comment by fubarhouse** [comment]
Seeking feedback on this one, I'll be merging in the next couple of days.

**Comment by issmirnov** [comment]
Nice! I looked over the series of commits. This new approach should make it easier to add future volumes. I hope that we won't need too many more, since at this point there's a flag for library, extra roles, and the playbook. That should probably cover most needs.

Excited to see this land!

**Comment by fubarhouse** [comment]
Yep! The idea is there will be a centralized location which manages this - so no arbitrary volume declarations, so we can prevent duplicates, add them to logging etc. It's generally useful to have this consolidated.

You've found nothing staking, so I'll process this one.
It's almost as exciting to me as the reporting mechanism 👍

**Comment by fubarhouse** [comment]
Closed in #57
