### ISSUE TITLE
Add Support for Fedora 29

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-tester#51]
Fedora 29 is now officially supported in the [Docker-Ansible](https://github.com/fubarhouse/docker-ansible) repository, so we can support it here.

This one's _very_ easy, so I'll mark it as a help wanted and good first issue - it's by means not a priority and we already have streamlined ways to use unsupported images.

**Comment by fubarhouse** [comment]
Example of current implementation/usage:
`ansible-role-tester full --custom --image fubarhouse/docker-ansible:fedora-29 --initialise /usr/lib/systemd/systemd`

**Comment by fubarhouse** [comment]
Despite the passing tests, this still needs to be addressed.

````
TASK [role_under_test : CURL | Install (RedHat)] *******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'
failed: [localhost] (item=[u'curl']) => {"changed": false, "item": ["curl"], "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_K2VUL9/ansible_module_dnf.py\", line 534, in <module>\n    main()\n  File \"/tmp/ansible_K2VUL9/ansible_module_dnf.py\", line 528, in main\n    params['releasever'])\n  File \"/tmp/ansible_K2VUL9/ansible_module_dnf.py\", line 245, in _base\n    base.fill_sack(load_system_repo='auto')\n  File \"/usr/lib/python2.7/site-packages/dnf/base.py\", line 403, in fill_sack\n    self.repos.all().disable()\n  File \"/usr/lib/python2.7/site-packages/dnf/lock.py\", line 147, in __exit__\n    os.unlink(self.target)\nOSError: [Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/etc/ansible/roles/role_under_test/tests/test-package.retry

PLAY RECAP *********************************************************************

localhost                  : ok=3    changed=0    unreachable=0    failed=1   
ERRO[0093] exit status 2
````

**Comment by issmirnov** [comment]
For debugging that error manually, you may find [this article](https://www.jeffgeerling.com/blog/2018/use-ansibles-yaml-callback-plugin-better-cli-experience) useful. It allows you to view the error as multiline yaml rather than a long string.

**Comment by fubarhouse** [comment]
See branch `issue/51` - this one should now be resolvable.
* https://travis-ci.org/fubarhouse/ansible-role-tester/builds/523016876
