### ISSUE TITLE
Optimization: Fail early

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/ansible-role-tester#69]
When running `ansible-role-tester full`, the following lines are executed:

```
report.Ansible.Syntax = dist.RoleSyntaxCheck(&config)
report.Ansible.Run.Result, report.Ansible.Run.Time = dist.RoleTest(&config)
report.Ansible.Idempotence.Result, report.Ansible.Idempotence.Time = dist.IdempotenceTest(&config)
```

However, in the event of broken syntax or a broken ansible run, it doesn't make sense to try and continue these tests.

Ideally the program should fail fast when it encounters failed syntax or a failed run. The downside is the code will be a little more verbose with more checks. On the upside this will make the output more readable.

**Comment by fubarhouse** [comment]
@issmirnov,

Could you look over the proposed solution when possible?

**Comment by issmirnov** [comment]
Added some comments. Looks great, with one minor mistake - the second flags should be `!report.Ansible.Run.Result`.
