### ISSUE TITLE
License says Apache 2.0

### ISSUE THREAD

**Issue by colonelpopcorn** [fubarhouse/ansible-role-tester#8]
This is really nit-picky but the README says that the license is MIT/BSD but the Github header and license file both say Apache 2.0 license. Which license is the code actually released under?

**Comment by fubarhouse** [comment]
@colonelpopcorn, `README.md` is out of date so I'll update it to match the various files generated by Cobra.

**Comment by colonelpopcorn** [comment]
Thanks! Looks really awesome, BTW!

**Comment by fubarhouse** [comment]
Thanks :) It has already throttled some of my work - enjoy!
