### ISSUE TITLE
Go 1.11 support

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-tester#94]
Update to ensure installation and execution are supported by version 1.11 of Go.

This update is subject to breaking backwards-compatibility, however it's not preferred...

* [x] Consider a Dockerfile as a secondary installation/execution method? (ensures dependency problems aren't our problems) - Future planning?
* [x] Update to work in Go 1.11
* [x] Update documentation to reflect any installation process changes
* [x] Update documentation to reflect any version requirements from this change
* [x] Update tests to reflect these changes

**Comment by issmirnov** [comment]
This seems quite reasonable. There's no particular reason I can think of that would require building from source using an old Golang toolchain. In the event that someone is on a legacy system, they can simply download and run a statically compiled release binary.

I haven't had a chance to play with Golang 11 modules yet, but IMO as long as tests pass and the binaries work as expected this should be an awesome upgrade.

HTH, thanks for the ping @fubarhouse!

**Comment by fubarhouse** [comment]
Causing problems with dependency updates, so it has been merged.
Thank you for your input.
